### ISSUE TITLE
Include license list from less to more restrictive.

### ISSUE THREAD

**Issue by jmtorralvo** [onebeyond/license-checker#3]
We'll use it for double licenses.

**Comment by inigomarquinez** [comment]
Most common licenses:

https://choosealicense.com/licenses/

**Comment by inigomarquinez** [comment]
How to specify a license in packaje.json: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license

When the package is licensed under multiple common licenses: https://www.npmjs.com/package/spdx

{
  "license" : "(ISC OR GPL-3.0)"
}

**Comment by inigomarquinez** [comment]
With the new way of supporting double licenses that we have added [here](https://github.com/onebeyond/license-checker/pull/66), this feature doesn't make sense any more. So we proceed to close the issue.
