### ISSUE TITLE
Make v.2.0.0 compatible with older version of node

### ISSUE THREAD

**Issue by dustytrinkets** [onebeyond/license-checker#47]
to avoid the following error we need to make the version 2.0.0 compatible with old node versions
![Screenshot 2022-05-04 at 12 23 52 (1)](https://user-images.githubusercontent.com/18383417/166664841-07fce928-d73d-42c7-92a8-5705ea0ef8a5.png)

**Comment by neodmy** [comment]
@inigomarquinez This is no longer an issue as this expression has been removed. Also, we don't use the optional chaining operator. I think we should close it.

**Comment by inigomarquinez** [comment]
You're right. Closing it!
